var path = require('path');
var rollup = require('rollup');
var rollupVue = require('rollup-plugin-vue');
var rollupJson = require('rollup-plugin-json');

var fileHelpers = require('./fileHelpers');

function build({ data, app, output }) {
  return Promise.all([
    generateJS({ data, app, output }),
    generateIndex({ title: data.title, output }),
  ]);
}

function generateJS({ data, app, output }) {
  return rollup.rollup({
    entry: app,
    plugins: [
      rollupVue({
        css: `${output}/novella.css`,
        compileTemplate: false,
      }),
      rollupJson(),
    ],
  }).then((bundle) => {
    bundle.write({
      format: 'iife',
      moduleName: 'Novella',
      indent: '  ',
      dest: `${output}/novella.js`,
      intro: `
console.log("Generated by novella at ${new Date().toLocaleString()}.");
var data = ${JSON.stringify(data)};\n`,
      globals: {vue: 'Vue'},
    });
  });
}

function generateIndex({ title, output }) {
  var templateLocation = path.resolve(__dirname, './app/index.html');
  var indexLocation = path.resolve(output, 'index.html');

  return fileHelpers.read(templateLocation)
  .then((file) => {
    var indexHTML = file.contents.replace('%TITLE%', title);
    return fileHelpers.write(indexLocation, indexHTML);
  });
}

module.exports = build;
