var path = require('path');
var exec = require('child_process').exec;
var rollup = require('rollup');
var rollupVue = require('rollup-plugin-vue');
var rollupJson = require('rollup-plugin-json');

var fileHelpers = require('./fileHelpers');

function build({ data, app, output }) {
  return Promise.all([
    generateJS({ data, app, output }),
    generateIndex({ title: data.title, output }),
    generateIcons({ output }),
  ]);
}

function generateJS({ data, app, output }) {
  return rollup.rollup({
    entry: app,
    plugins: [
      rollupVue({
        css: `${output}/novella.css`,
        compileTemplate: false,
      }),
      rollupJson(),
    ],
  }).then((bundle) => {
    bundle.write({
      format: 'iife',
      moduleName: 'Novella',
      indent: '  ',
      dest: `${output}/novella.js`,
      intro: `
console.log("Generated by novella at ${new Date().toLocaleString()}.");
var data = ${JSON.stringify(data)};\n`,
      globals: {vue: 'Vue'},
    });
  });
}

function generateIndex({ title, output }) {
  var templateLocation = path.resolve(__dirname, './app/index.html');
  var indexLocation = path.resolve(output, 'index.html');

  return fileHelpers.read(templateLocation)
  .then((file) => {
    var indexHTML = file.contents.replace('%TITLE%', title);
    return fileHelpers.write(indexLocation, indexHTML);
  });
}

function generateIcons({ output }) {
  var iconsDir = path.resolve(__dirname, '../icons');
  return fileHelpers.mkdir(`${output}/icons/`)
    .catch(() => {}) // Ignore mkdir errors
    .then(() => Promise.all([
        execute(`cp -r ${iconsDir}/font ${output}/icons/font`),
        execute(`cp -r ${iconsDir}/css ${output}/icons/css`),
      ])
    );
}

function execute(command, ignoreError) {
  return new Promise((res, rej) => {
    exec(command, (err, stdout) => {
      if (err && !ignoreError) rej(err);
      res(stdout);
    });
  });
}

module.exports = build;
